controller_list:
  - name: fake_keti_robot_controller
    type: $(arg fake_execution_type)
    joints:
      - q1
      - q2
      - q3
      - q4
      - q5
      - q6
  - name: fake_keti_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - slide_finger1
      - slide_finger2
initial:  # Define initial robot poses per group
  - group: keti_robot
    pose: robot_init
  - group: keti_gripper
    pose: gripper_init