keti_robot_arm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  q1_position_controller:
    type: position_controllers/JointPositionController
    joint: q1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  q2_position_controller:
    type: position_controllers/JointPositionController
    joint: q2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  q3_position_controller:
    type: position_controllers/JointPositionController
    joint: q3
    pid: {p: 100.0, i: 0.01, d: 10.0}
  q4_position_controller:
    type: position_controllers/JointPositionController
    joint: q4
    pid: {p: 100.0, i: 0.01, d: 10.0}
  q5_position_controller:
    type: position_controllers/JointPositionController
    joint: q5
    pid: {p: 100.0, i: 0.01, d: 10.0}
  q6_position_controller:
    type: position_controllers/JointPositionController
    joint: q6
    pid: {p: 100.0, i: 0.01, d: 10.0}
  s1_position_controller:
    type: position_controllers/JointPositionController
    joint: s1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  s2_position_controller:
    type: position_controllers/JointPositionController
    joint: s2
    pid: {p: 100.0, i: 0.01, d: 10.0}